//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCounter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyCounter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey Counter.
        /// </summary>
        public static string TXT_APP_TITLE {
            get {
                return ResourceManager.GetString("TXT_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add counter.
        /// </summary>
        public static string TXT_BUTTON_ADD {
            get {
                return ResourceManager.GetString("TXT_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TXT_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("TXT_BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string TXT_BUTTON_DONE {
            get {
                return ResourceManager.GetString("TXT_BUTTON_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide overlay.
        /// </summary>
        public static string TXT_BUTTON_OVERLAY_HIDE {
            get {
                return ResourceManager.GetString("TXT_BUTTON_OVERLAY_HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show overlay.
        /// </summary>
        public static string TXT_BUTTON_OVERLAY_SHOW {
            get {
                return ResourceManager.GetString("TXT_BUTTON_OVERLAY_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string TXT_BUTTON_RESET {
            get {
                return ResourceManager.GetString("TXT_BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string TXT_HEADER_COUNTER {
            get {
                return ResourceManager.GetString("TXT_HEADER_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string TXT_HEADING_COLOR {
            get {
                return ResourceManager.GetString("TXT_HEADING_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit count by double click on it.
        /// </summary>
        public static string TXT_HINT_EDIT {
            get {
                return ResourceManager.GetString("TXT_HINT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string TXT_LABEL_BACKGROUND {
            get {
                return ResourceManager.GetString("TXT_LABEL_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string TXT_LABEL_FONT {
            get {
                return ResourceManager.GetString("TXT_LABEL_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        public static string TXT_LABEL_HOTKEY {
            get {
                return ResourceManager.GetString("TXT_LABEL_HOTKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TXT_LABEL_NAME {
            get {
                return ResourceManager.GetString("TXT_LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New counter.
        /// </summary>
        public static string TXT_NEW_COUNTER {
            get {
                return ResourceManager.GetString("TXT_NEW_COUNTER", resourceCulture);
            }
        }
    }
}
